const DATA_TYPE_SQL = {

    INTEGER: "INTEGER",
    DECIMAL: "DECIMAL",
    VARCHAR: "VARCHAR",
    TEXT: "TEXT",
    BOOLEAN: "BOOLEAN",
    DATE: "DATE",
    TIMESTAMP: "TIMESTAMP",

};

const ALLOWED_DATA_TYPES = Object.keys(DATA_TYPE_SQL);

export function quoteIdentifier(identifier) {

    return `"${identifier.replace(/"/g, '""')}"`;

}

export function validateTableName(name) {

    if (!name || typeof name !== "string") {

        throw new Error("Table name is required.");

    }

    const trimmedName = name.trim();

    if (!trimmedName) {

        throw new Error("Table name is required.");

    }

    if (trimmedName.length > 63) {

        throw new Error(
            "Table name cannot exceed 63 characters."
        );

    }

    return trimmedName;

}

export function validateColumnDefinitions(columns) {

    if (!Array.isArray(columns)) {

        return [];

    }

    const names = new Set();

    for (const column of columns) {

        if (!column.name || typeof column.name !== "string") {

            throw new Error(
                "Every column must have a name."
            );

        }

        const name = column.name.trim();

        if (!name) {

            throw new Error(
                "Every column must have a name."
            );

        }

        if (name.length > 63) {

            throw new Error(
                `Column name "${name}" cannot exceed 63 characters.`
            );

        }

        const normalizedName = name.toLowerCase();

        if (names.has(normalizedName)) {

            throw new Error(
                `Column name "${name}" is duplicated.`
            );

        }

        names.add(normalizedName);

        if (!ALLOWED_DATA_TYPES.includes(column.dataType)) {

            throw new Error(
                `Invalid data type for column "${name}".`
            );

        }

        if (
            column.isAutoIncrement &&
            column.dataType !== "INTEGER"
        ) {

            throw new Error(
                `Auto increment is only supported for INTEGER columns.`
            );

        }

        if (
            column.isAutoIncrement &&
            !column.isPrimaryKey
        ) {

            throw new Error(
                `Auto increment column "${name}" must be a primary key.`
            );

        }

    }

    const primaryKeys = columns.filter(
        column => column.isPrimaryKey
    );

    if (primaryKeys.length > 1) {

        throw new Error(
            "A table can only have one primary key."
        );

    }

    return columns;

}

function buildDefaultValue(column) {

    const value = column.defaultValue;

    if (
        value === null ||
        value === undefined ||
        String(value).trim() === ""
    ) {

        return "";

    }

    const defaultValue = String(value).trim();

    if (column.dataType === "BOOLEAN") {

        if (
            defaultValue !== "true" &&
            defaultValue !== "false"
        ) {

            throw new Error(
                `Invalid BOOLEAN default value for "${column.name}".`
            );

        }

        return ` DEFAULT ${defaultValue}`;

    }

    if (
        column.dataType === "INTEGER" ||
        column.dataType === "DECIMAL"
    ) {

        if (!/^-?\d+(\.\d+)?$/.test(defaultValue)) {

            throw new Error(
                `Invalid numeric default value for "${column.name}".`
            );

        }

        return ` DEFAULT ${defaultValue}`;

    }

    if (
        column.dataType === "TIMESTAMP" &&
        defaultValue === "CURRENT_TIMESTAMP"
    ) {

        return " DEFAULT CURRENT_TIMESTAMP";

    }

    return ` DEFAULT '${defaultValue.replace(/'/g, "''")}'`;

}

export function buildCreateTableSQL(tableName, columns) {

    const columnDefinitions = columns.map(column => {

        const parts = [

            quoteIdentifier(column.name),

        ];

        if (column.isAutoIncrement) {

            parts.push(
                "INTEGER GENERATED BY DEFAULT AS IDENTITY"
            );

        } else {

            parts.push(
                DATA_TYPE_SQL[column.dataType]
            );

        }

        if (column.isNullable === false) {

            parts.push("NOT NULL");

        }

        if (column.isUnique) {

            parts.push("UNIQUE");

        }

        const defaultValue =
            buildDefaultValue(column);

        if (defaultValue) {

            parts.push(defaultValue);

        }

        if (column.isPrimaryKey) {

            parts.push("PRIMARY KEY");

        }

        return parts.join(" ");

    });

    return `
        CREATE TABLE ${quoteIdentifier(tableName)} (
            ${columnDefinitions.join(",\n            ")}
        );
    `;

}

export function validateSingleColumnDefinition(column) {

    const validatedColumns =
        validateColumnDefinitions([column]);

    return validatedColumns[0];

}